### ISSUE TITLE
key pressed detection is not working

### ISSUE THREAD

**Issue by pissard** [BirdLogics/sb3topy#3]
The key pressed detection is not working. I correct this bug in the fork project:  https://github.com/autonabee/sb3topy

A example requiring to press the key space to move the cat.

[cat.sb3.zip](https://github.com/BirdLogics/sb3topy/files/11031898/cat.sb3.zip)

**Comment by BirdLogics** [comment]
Yep, it looks like I miss named the events. This is now fixed on the dev branch.
