### ISSUE TITLE
svg convert

### ISSUE THREAD

**Issue by PhawatPK** [BirdLogics/sb3topy#9]
[INFO] Extracting project...
[INFO] Converting project assets...
[WARNING] Package cairosvg is not installed correctly.
[ERROR] SVG conversion is enabled but cairosvg does not appear to be installed. Consider configuring Inkscape under Asset settings in the GUI.
[WARNING] Costume conversion is disabled. Any SVGs in the project will not be visible.
[INFO] Overwriting engine files at 'C:/Users/kaisu/Downloads\engine'
[INFO] Compiling project into Python...
[INFO] Initializing parser...
[INFO] Running optimizations...
[INFO] Generating Python code...
[INFO] Saving converted project to 'C:/Users/kaisu/Downloads\project.py'
[INFO] Finished converting project. Saved in 'C:/Users/kaisu/Downloads'
[INFO] Running project...
[INFO] Done!

**Comment by BirdLogics** [comment]
It looks like you don't have CarioSVG installed. You can install it with `pip install cariosvg`. I do plan to add support for Pygame SVGs though, so I'll leave this open.
